name: Hello
on: push
jobs:
  gs-ls:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/auth@v2
        with:
          project_id: 'wacwac-staging'
          workload_identity_provider: 'projects/355206167652/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-oidc'
          service_account: 'git-hub-actions@wacwac-staging.iam.gserviceaccount.com'
      - run: cat $GOOGLE_APPLICATION_CREDENTIALS
      - run: gcloud auth activate-service-account --key-file="$GOOGLE_APPLICATION_CREDENTIALS"
      - run: gcloud auth list 
      - run: gcloud storage ls gs://wacwac-staging-secret-store


