name: Hello
on: push
jobs:
  gs-ls:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: 'projects/355206167652/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-oidc'
          service_account: 'git-hub-actions@wacwac-staging.iam.gserviceaccount.com'

      - run: gcloud storage ls gs://wacwac-staging-secret-store


